app = "weeklyroulette-slack-bot"
primary_region = "fra"

[build]

[[mounts]]
source = "weeklyroulette_data"
destination = "/data"

[processes]
app = "./weeklyroulette"

[vm]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
