app = "weeklyroulette-slack-bot"
primary_region = "fra"

[build]

[env]

[[mounts]]
source = "weeklyroulette_data"
destination = "/data"


[processes]
app = "python -m main"

[vm]
cpu_kind = "shared"
cpus = 1
memory_mb = 256
